:github-tag: master
:github-repo: spring-cloud/spring-cloud-openfeign
:github-raw: http://raw.github.com/{github-repo}/{github-tag}
:github-code: http://github.com/{github-repo}/tree/{github-tag}
:all: {asterisk}{asterisk}
:nofooter:
:branch: master
= Spring Cloud OpenFeign

*{spring-cloud-version}*

include::intro.adoc[]


[[spring-cloud-feign]]
== Declarative reactive REST Client: ReactiveFeign

ReactiveFeign is a reactive web service client.  It makes writing web service clients easier.  To use ReactiveFeign create an interface and proxy it using FeignBuilder.

[[netflix-feign-starter]]
=== How to Include ReactiveFeign

To include ReactiveFeign in your project use the starter with group `org.springframework.cloud`
and artifact id `spring-cloud-starter-openfeign`. See the http://projects.spring.io/spring-cloud/[Spring Cloud Project page]
for details on setting up your build system with the current Spring Cloud Release Train.

.StoreClient.java
[source,java,indent=0]
----
public interface StoreClient {
    @RequestLine("GET /stores")
    List<Store> getStores();

    @RequestLine("POST /stores/{storeId}")
    @Headers({ "Content-Type: application/json" })
    Store update(@Param("storeId") Long storeId, Store store);
}
----

=== Creating ReactiveFeign Clients Manually

Currently the only supported way to create ReactiveFeign client  is to use ReactiveFeign.Builder
Below is an example which creates two reactive Feign Clients with the same interface but configures each one with
a separate request interceptor.

[source,java,indent=0]
----

FooClient fooClient = ReactiveFeign.<FooClient>builder()
        .requestInterceptor(request -> {
            request.headers().add("Authorization", "Bearer mytoken123");
            return request;
        }).target(FooClient.class, "http://PROD-SVC");

FooClient adminClient = ReactiveFeign.<FooClient>builder()
        .requestInterceptor(request -> {
            request.headers().add("Authorization", "Bearer admin_token");
            return request;
        }).target(FooClient.class, targetUrl);

----

=== Status handler

Custom logic to process http responses with specific http status

[source,java]
----
FooClient clientWithoutAuth = ReactiveFeign.<FooClient>builder()
        .statusHandler(new ReactiveStatusHandler() {
            @Override
            public boolean shouldHandle(org.springframework.http.HttpStatus status) {
                return status.value() == HttpStatus.SC_SERVICE_UNAVAILABLE;
            }
            @Override
            public Mono<? extends Throwable> decode(String methodKey, ClientResponse response) {
                return Mono.just(new RetryableException("Should retry", null));
            }
        })
        .target(FooClient.class, targetUrl);
----

=== decode404

This flag indicates that the reactive feign client should process responses with 404 status, specifically returning empty {@link Mono} or {@link Flux} instead of throwing {@link FeignException}.

[source,java]
----
FooClient clientWithAuth = ReactiveFeign.<FooClient>builder()
        .requestInterceptor(request -> {
            request.headers().add("Authorization", "Bearer mytoken123");
            return request;
        }).target(FooClient.class, targetUrl);
----

=== Request interceptor

Set request interceptor to set specific header to client requests. Basically used to set auth headers.

[source,java]
----
FooClient clientWithAuth = ReactiveFeign.<FooClient>builder()
        .requestInterceptor(request -> {
            request.headers().add("Authorization", "Bearer mytoken123");
            return request;
        }).target(FooClient.class, targetUrl);
----

=== Retry policy

Allows to retry request on error response

[source,java]
----
IcecreamServiceApi client = ReactiveFeign.<IcecreamServiceApi>builder()
        .retryWhen(ReactiveRetryers.retryWithBackoff(3, 10))
        .target(IcecreamServiceApi.class,
                "http://localhost:" + wireMockRule.port());
----

=== Read/connect timeout

Restricts time to connect or wait for response for web client

[source,java]
----
IcecreamServiceApi client = ReactiveFeign.<IcecreamServiceApi>builder()
        .options(new ReactiveOptions.Builder()
                .setConnectTimeoutMillis(300)
                .setReadTimeoutMillis(100)
                .build())
        .target(IcecreamServiceApi.class,
                "http://localhost:" + wireMockRule.port());
----

=== Request/response compression

You may consider enabling the request or response GZIP compression for your reactive Feign requests. You can do this by enabling one of the properties:

[source,java]
----
FooClient client = ReactiveFeign.<FooClient>builder()
        .options(new ReactiveOptions.Builder().setTryUseCompression(true).build())
        .target(FooClient.class, targetUrl);
----

=== Custom web client

You may set custom web client implementation:

[source,java]
----
IcecreamServiceApi client = ReactiveFeign.<IcecreamServiceApi>builder()
        .webClient(WebClient.create())
        .target(FooClient.class, targetUrl);
----


[[spring-cloud-feign-inheritance]]
=== Inheritance Support

ReactiveFeign supports boilerplate apis via single-inheritance interfaces. This allows grouping common operations into convenient base interfaces.

.UserService.java
[source,java,indent=0]
----
public interface UserService {
    User getUser(long id);
}
----

.UserResource.java
[source,java,indent=0]
----
@RestController
public class UserResource implements UserService {

    @Override
    @RequestMapping(method = RequestMethod.GET, value ="/users/{id}")
    User getUser(@PathVariable("id") long id);
}
----

.UserClient.java
[source,java,indent=0]
----
package project.user;

public interface UserClient extends UserService {

    @Override
    @RequestLine("POST /users/{id}")
    User getUser(@Param("id") long id);
}
----


