/*
 * Copyright 2013-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package org.springframework.cloud.openfeign.encoding.proto;

public final class ProtobufTest {

	private ProtobufTest() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

	static {
		String[] descriptorData = {
				"\n\rrequest.proto\0222org.springframework.clo" + "ud.openfeign.encoding.proto\"\"\n\007Request\022\n"
						+ "\n\002id\030\001 \001(\005\022\013\n\003msg\030\002 \001(\tBD\n2org.springfra"
						+ "mework.cloud.openfeign.encoding.protoB\014P" + "rotobufTestP\001b\006proto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_descriptor = getDescriptor()
			.getMessageTypes()
			.get(0);
		internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_descriptor,
				new String[] { "Id", "Msg", });
	}

	// @@protoc_insertion_point(outer_class_scope)

}
