/*
 * Copyright 2013-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package org.springframework.cloud.openfeign.encoding.proto;

/**
 * Protobuf type {@code org.springframework.cloud.openfeign.encoding.proto.Request}
 */
public final class Request extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:org.springframework.cloud.openfeign.encoding.proto.Request)
		RequestOrBuilder {

	private static final long serialVersionUID = 0L;

	// Use Request.newBuilder() to construct.
	private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private Request() {
		msg_ = "";
	}

	@Override
	@SuppressWarnings({ "unused" })
	protected Object newInstance(UnusedPrivateParameter unused) {
		return new Request();
	}

	@Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return ProtobufTest.internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_descriptor;
	}

	@Override
	protected FieldAccessorTable internalGetFieldAccessorTable() {
		return ProtobufTest.internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_fieldAccessorTable
			.ensureFieldAccessorsInitialized(Request.class, Builder.class);
	}

	public static final int ID_FIELD_NUMBER = 1;

	private int id_ = 0;

	/**
	 * <code>int32 id = 1;</code>
	 * @return The id.
	 */
	@Override
	public int getId() {
		return id_;
	}

	public static final int MSG_FIELD_NUMBER = 2;

	@SuppressWarnings("serial")
	private volatile Object msg_ = "";

	/**
	 * <code>string msg = 2;</code>
	 * @return The msg.
	 */
	@Override
	public String getMsg() {
		Object ref = msg_;
		if (ref instanceof String) {
			return (String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			String s = bs.toStringUtf8();
			msg_ = s;
			return s;
		}
	}

	/**
	 * <code>string msg = 2;</code>
	 * @return The bytes for msg.
	 */
	@Override
	public com.google.protobuf.ByteString getMsgBytes() {
		Object ref = msg_;
		if (ref instanceof String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
			msg_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	@Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (id_ != 0) {
			output.writeInt32(1, id_);
		}
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
		}
		getUnknownFields().writeTo(output);
	}

	@Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (id_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
		}
		if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
		}
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@Override
	public boolean equals(final Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof Request)) {
			return super.equals(obj);
		}
		Request other = (Request) obj;

		if (getId() != other.getId())
			return false;
		if (!getMsg().equals(other.getMsg()))
			return false;
		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + ID_FIELD_NUMBER;
		hash = (53 * hash) + getId();
		hash = (37 * hash) + MSG_FIELD_NUMBER;
		hash = (53 * hash) + getMsg().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static Request parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static Request parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static Request parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static Request parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static Request parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static Request parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static Request parseFrom(java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static Request parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static Request parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static Request parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static Request parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static Request parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(Request prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@Override
	protected Builder newBuilderForType(BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code org.springframework.cloud.openfeign.encoding.proto.Request}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:org.springframework.cloud.openfeign.encoding.proto.Request)
			RequestOrBuilder {

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return ProtobufTest.internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_descriptor;
		}

		@Override
		protected FieldAccessorTable internalGetFieldAccessorTable() {
			return ProtobufTest.internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_fieldAccessorTable
				.ensureFieldAccessorsInitialized(Request.class, Builder.class);
		}

		// Construct using
		// org.springframework.cloud.openfeign.encoding.proto.Request.newBuilder()
		private Builder() {

		}

		private Builder(BuilderParent parent) {
			super(parent);

		}

		@Override
		public Builder clear() {
			super.clear();
			bitField0_ = 0;
			id_ = 0;
			msg_ = "";
			return this;
		}

		@Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return ProtobufTest.internal_static_org_springframework_cloud_openfeign_encoding_proto_Request_descriptor;
		}

		@Override
		public Request getDefaultInstanceForType() {
			return Request.getDefaultInstance();
		}

		@Override
		public Request build() {
			Request result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@Override
		public Request buildPartial() {
			Request result = new Request(this);
			if (bitField0_ != 0) {
				buildPartial0(result);
			}
			onBuilt();
			return result;
		}

		private void buildPartial0(Request result) {
			int from_bitField0_ = bitField0_;
			if (((from_bitField0_ & 0x00000001) != 0)) {
				result.id_ = id_;
			}
			if (((from_bitField0_ & 0x00000002) != 0)) {
				result.msg_ = msg_;
			}
		}

		@Override
		public Builder clone() {
			return super.clone();
		}

		@Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
			return super.setField(field, value);
		}

		@Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
			return super.addRepeatedField(field, value);
		}

		@Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof Request) {
				return mergeFrom((Request) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(Request other) {
			if (other == Request.getDefaultInstance())
				return this;
			if (other.getId() != 0) {
				setId(other.getId());
			}
			if (!other.getMsg().isEmpty()) {
				msg_ = other.msg_;
				bitField0_ |= 0x00000002;
				onChanged();
			}
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@Override
		public final boolean isInitialized() {
			return true;
		}

		@Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {
							id_ = input.readInt32();
							bitField0_ |= 0x00000001;
							break;
						} // case 8
						case 18: {
							msg_ = input.readStringRequireUtf8();
							bitField0_ |= 0x00000002;
							break;
						} // case 18
						default: {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			}
			finally {
				onChanged();
			} // finally
			return this;
		}

		private int bitField0_;

		private int id_;

		/**
		 * <code>int32 id = 1;</code>
		 * @return The id.
		 */
		@Override
		public int getId() {
			return id_;
		}

		/**
		 * <code>int32 id = 1;</code>
		 * @param value The id to set.
		 * @return This builder for chaining.
		 */
		public Builder setId(int value) {

			id_ = value;
			bitField0_ |= 0x00000001;
			onChanged();
			return this;
		}

		/**
		 * <code>int32 id = 1;</code>
		 * @return This builder for chaining.
		 */
		public Builder clearId() {
			bitField0_ = (bitField0_ & ~0x00000001);
			id_ = 0;
			onChanged();
			return this;
		}

		private Object msg_ = "";

		/**
		 * <code>string msg = 2;</code>
		 * @return The msg.
		 */
		public String getMsg() {
			Object ref = msg_;
			if (!(ref instanceof String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				msg_ = s;
				return s;
			}
			else {
				return (String) ref;
			}
		}

		/**
		 * <code>string msg = 2;</code>
		 * @return The bytes for msg.
		 */
		public com.google.protobuf.ByteString getMsgBytes() {
			Object ref = msg_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				msg_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string msg = 2;</code>
		 * @param value The msg to set.
		 * @return This builder for chaining.
		 */
		public Builder setMsg(String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			msg_ = value;
			bitField0_ |= 0x00000002;
			onChanged();
			return this;
		}

		/**
		 * <code>string msg = 2;</code>
		 * @return This builder for chaining.
		 */
		public Builder clearMsg() {
			msg_ = getDefaultInstance().getMsg();
			bitField0_ = (bitField0_ & ~0x00000002);
			onChanged();
			return this;
		}

		/**
		 * <code>string msg = 2;</code>
		 * @param value The bytes for msg to set.
		 * @return This builder for chaining.
		 */
		public Builder setMsgBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);
			msg_ = value;
			bitField0_ |= 0x00000002;
			onChanged();
			return this;
		}

		@Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:org.springframework.cloud.openfeign.encoding.proto.Request)

	}

	// @@protoc_insertion_point(class_scope:org.springframework.cloud.openfeign.encoding.proto.Request)
	private static final Request DEFAULT_INSTANCE;

	static {
		DEFAULT_INSTANCE = new Request();
	}

	public static Request getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<Request> PARSER = new com.google.protobuf.AbstractParser<Request>() {
		@Override
		public Request parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			}
			catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
					.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<Request> parser() {
		return PARSER;
	}

	@Override
	public com.google.protobuf.Parser<Request> getParserForType() {
		return PARSER;
	}

	@Override
	public Request getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
