/*
 * Copyright 2013-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package org.springframework.cloud.openfeign.encoding.proto;

public interface RequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:org.springframework.cloud.openfeign.encoding.proto.Request)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>int32 id = 1;</code>
	 * @return The id.
	 */
	int getId();

	/**
	 * <code>string msg = 2;</code>
	 * @return The msg.
	 */
	String getMsg();

	/**
	 * <code>string msg = 2;</code>
	 * @return The bytes for msg.
	 */
	com.google.protobuf.ByteString getMsgBytes();

}
