# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ 3.1.x ]
  pull_request:
    branches: [ 3.1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ["8", "11", "16"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw clean install -B -U -P sonar
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
